
version: 0.2

phases:
#   install:
#     docker
      
#   pre_build:
#     commands:
#       - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - docker build -t custom-node/mysql .
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
