
version: 0.2

phases:
#   install:
#     docker
      
#   pre_build:
#     commands:
#       - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - docker build -t custom-nodejs/mysql .
      - docker images
      - docker --version
     
  post_build:
      - docker run -d -p 3000:3000 --name myapp custom-nodejs/mysql
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
